## MB-iSTFT-VITS2 inference

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import IPython.display as ipd
import librosa

import os
import json
import math

import requests
import torch
import torchaudio
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader

import commons
import utils
from data_utils_speaker_tone_lang import TextAudioSpeakerToneLangLoader, TextAudioSpeakerToneLangCollate
from models import SynthesizerTrn
from text.symbols import symbols
from text import text_to_sequence

from scipy.io.wavfile import write
import re

In [3]:
#- device setting
if torch.cuda.is_available() is True:
    device = "cuda:0"
else:
    device = "cpu"

In [4]:
def file_to_mel(file_path, 
                target_sr=22050, 
                n_mels=80, 
                n_fft=1024, 
                hop_length=256, 
                win_length=1024, 
                fmin=0.0, 
                fmax=8000.0,
                normalize_audio=True):
    """
    Loads an audio file and converts it to a Mel Spectrogram.
    """
    # 1. Load the audio
    # waveform shape: [channels, time]
    waveform, sr = torchaudio.load(file_path)

    # 2. Resample if necessary
    if sr != target_sr:
        resampler = torchaudio.transforms.Resample(orig_freq=sr, new_freq=target_sr)
        waveform = resampler(waveform)

    # 3. Normalize Audio (Matches: audio_norm = audio / self.max_wav_value)
    # Most wav files load as -1 to 1 float, but if you need specific scaling:
    if normalize_audio:
        # This ensures the audio is within [-1, 1]
        waveform = torch.clamp(waveform, min=-1.0, max=1.0)

    # 4. Define the Mel Spectrogram Transform
    # center=False matches the snippet provided
    mel_transform = torchaudio.transforms.MelSpectrogram(
        sample_rate=target_sr,
        n_fft=n_fft,
        win_length=win_length,
        hop_length=hop_length,
        f_min=fmin,
        f_max=fmax,
        n_mels=n_mels,
        center=False, 
        power=1.0 # 1.0 for magnitude, 2.0 for power. Tacotron usually uses 1.0
    )

    # 5. Generate Mel Spec
    mel_spec = mel_transform(waveform)

    # 6. Logarithmic Compression (Dynamic Range Compression)
    # The snippet's `mel_spectrogram_torch` usually implies a log operation.
    # We clamp to avoid log(0).
    mel_spec = torch.log(torch.clamp(mel_spec, min=1e-5))

    return mel_spec

In [5]:
def get_text(text, hps, lid):
    lang_code = "ky" if lid == 0 else "ru"
    text_norm = text_to_sequence(text, hps.data.text_cleaners, lang_code)
    if hps.data.add_blank:
        text_norm = commons.intersperse(text_norm, 0)
    text_norm = torch.LongTensor(text_norm)
    return text_norm

def vcms(inputstr, sid, tid, lid, spec_ref): # multi
    fltstr = re.sub(r"[\[\]\(\)\{\}]", "", inputstr)
    #fltstr = langdetector(fltstr) #- optional for cjke/cjks type cleaners
    stn_tst = get_text(fltstr, hps, lid)

    speed = 1
    with torch.no_grad():
        x_tst = stn_tst.to(device).unsqueeze(0)
        x_tst_lengths = torch.LongTensor([stn_tst.size(0)]).to(device)
        sid = torch.LongTensor([sid]).to(device)
        tid = torch.LongTensor([tid]).to(device)
        lid = torch.LongTensor([lid]).to(device)
        audio = net_g.infer(x_tst, x_tst_lengths, y=spec_ref, sid=sid, tid=tid, lid=lid, noise_scale=0.67, noise_scale_w=0.8, length_scale=1 / speed)[0][
            0, 0].data.cpu().float().numpy()

    print(audio)
    ipd.display(ipd.Audio(audio, rate=hps.data.sampling_rate, normalize=True))

In [6]:
# - paths
path_to_config = "/mnt/d/elevenlabs/config.json" 
path_to_model = "/mnt/d/elevenlabs/G_139800.pth"  

path_to_config = "/mnt/d/super_last/config.json" 
path_to_model = "/mnt/d/super_last/G_688000.pth"

# path_to_config = "/mnt/d/youtube/config.json" 
# path_to_model = "/mnt/d/youtube/G_42000.pth"

# path_to_config = "/home/k_arzymatov/PycharmProjects/VITS100/logs/mbank_sdp/config.json" 
# path_to_model = "/home/k_arzymatov/PycharmProjects/VITS100/logs/mbank_sdp/G_98000.pth"

In [7]:
hps = utils.get_hparams_from_file(path_to_config)

if "use_mel_posterior_encoder" in hps.model.keys() and hps.model.use_mel_posterior_encoder == True:
    print("Using mel posterior encoder for VITS2")
    posterior_channels = 80  # vits2
    hps.data.use_mel_posterior_encoder = True
else:
    print("Using lin posterior encoder for VITS1")
    posterior_channels = hps.data.filter_length // 2 + 1
    hps.data.use_mel_posterior_encoder = False

net_g = SynthesizerTrn(
    len(symbols),
    posterior_channels,
    hps.train.segment_size // hps.data.hop_length,
    **hps.model).to(device)
_ = net_g.eval()

_ = utils.load_checkpoint(path_to_model, net_g, None)

Using mel posterior encoder for VITS2
Multi-band iSTFT VITS2


/home/k_arzymatov/miniconda3/envs/universal_models_312/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [8]:
total_params = sum(p.numel() for p in net_g.parameters())
print(total_params)

40404465


In [9]:
# ref_audio = "/mnt/d/elevenlabs_generate_kyrgyz_voices/output/noble_butler/00001_001_news_01-05_007_1_Timur_neutral_kg.wav"
# spec_filename = "/mnt/d/elevenlabs_generate_kyrgyz_voices/output/noble_butler/00001_001_news_01-05_007_1_Timur_neutral_kg.mel.pt"

# ref_audio = "/mnt/d/data_gathering_diarization_cleaning/output/2cTytn8JvZA/segments/SPEAKER_00/segment_0001.wav"
# spec_ref =  file_to_mel(ref_audio).to(device)

# ref_audio = "/mnt/d/studio_audio_flat/wavs/00000_000_inter_sounds_neutral_040_1_Aiganysh_strict_kg.wav"
# ref_audio = "/mnt/d/00000_000_addresses_004_1_Timur_neutral_kg.wav"

# ref_audio = "/mnt/d/qwen_girl1.wav"
# spec_ref =  file_to_mel(ref_audio).to(device)


# spec_filename = "/mnt/d/00189_008_ru_general_044_19_Timur_neutral_ru.mel.pt"
# audio_filename = "/mnt/d/00000_000_addresses_004_1_Timur_neutral_kg.wav"
spec_filename = "/mnt/d/00000_000_addresses_004_1_Timur_neutral_kg.mel.pt"
spec_ref = torch.load(spec_filename, weights_only=True).to(device).unsqueeze(0)

In [14]:
spec_ref

tensor([[[-6.7730, -5.2313, -4.3668,  ..., -3.2346, -2.8302, -2.8064],
         [-6.8437, -5.3293, -5.0779,  ..., -4.2839, -4.1580, -4.2222],
         [-7.0000, -5.8302, -5.7038,  ..., -5.2028, -5.5064, -5.4850],
         ...,
         [-9.8671, -9.7824, -9.8932,  ..., -9.8730, -9.8579, -9.7493],
         [-9.8819, -9.7982, -9.8713,  ..., -9.8862, -9.8970, -9.6812],
         [-9.9462, -9.9155, -9.9347,  ..., -9.9306, -9.9557, -9.7939]]],
       device='cuda:0')

In [68]:
ipd.display(ipd.Audio(ref_audio, rate=hps.data.sampling_rate, normalize=False))

In [ ]:
c = " рыноктук шартка ылайыкташкан ушул ишканалар өнөр жай , курулуш , транспорт , соода же тейлөөнүн башка тармактарына таандык . "
# c = "бишкек"
# c = " <cough> сураныч мен максат эмесмин . "
# c = "Главный транспортный узел, промышленный и административный центр страны. Современный культурный, политический и экономический центр республики."
# c = "шаардын жаныбарлар дүйнөсүнүн негизин палеарктикалык ландшафттын маданий фаунасынын типтүү өкүлдөрү түзөт. сүт эмүүчүлөрдүн негизгилери жарганаттар."
vcms(c, sid=0, tid=1, lid=0, spec_ref=spec_ref)

[ 0.00018702  0.00013437  0.00033439 ...  0.000542    0.00035927
 -0.00021094]


In [28]:
net_g.ref_enc

ReferenceEncoder(
  (convs): ModuleList(
    (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (1): Conv2d(32, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (2): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (4): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (5): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
  )
  (gru): GRU(256, 128, batch_first=True)
  (proj): Linear(in_features=128, out_features=256, bias=True)
)

In [63]:
timur_audio_1 = "/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep_34_Timur_neutral_kg.wav"
timur_spec_1 = torch.load("/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep_34_Timur_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_timur_1 = net_g.ref_enc(timur_spec_1)

timur_audio_2 = "/mnt/d/studio_audio_flat/wavs/00318_007_sales_001_commas_sep_31_Timur_neutral_kg.wav"
timur_spec_2 = torch.load("/mnt/d/studio_audio_flat/wavs/00318_007_sales_001_commas_sep_31_Timur_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_timur_2 = net_g.ref_enc(timur_spec_2)

aiganysh_audio_1 = "/mnt/d/studio_audio_flat/wavs/00349_007_sales_001_commas_sep_35_Aiganysh_strict_kg.wav"
aiganysh_spec_1 = torch.load("/mnt/d/studio_audio_flat/wavs/00349_007_sales_001_commas_sep_35_Aiganysh_strict_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_aiganysh_1 = net_g.ref_enc(aiganysh_spec_1)

aiganysh_audio_2 = "/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep-2_35_Aiganysh_neutral_kg.wav"
aiganysh_spec_2 = torch.load("/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep-2_35_Aiganysh_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_aiganysh_2 = net_g.ref_enc(aiganysh_spec_2)

# random_audio_1 = "/mnt/d/data_gathering_diarization_cleaning/output/2cTytn8JvZA/segments/SPEAKER_00/segment_0001.wav"
# random_spec_1 =  file_to_mel(random_audio_1).to(device)
# g_random_1 = net_g.ref_enc(random_spec_1)

# random_audio_2 = "/mnt/d/qwen_girl1.wav"
# random_spec_2 =  file_to_mel(random_audio_2).to(device)
# g_random_2 = net_g.ref_enc(random_audio_2)

In [64]:
g_timur_1.shape

torch.Size([1, 256])

In [65]:
print(F.cosine_similarity(g_timur_1, g_timur_2))
print(F.cosine_similarity(g_aiganysh_1, g_aiganysh_2))
print(F.cosine_similarity(g_timur_1, g_aiganysh_1))
print(F.cosine_similarity(g_timur_2, g_aiganysh_2))

tensor([0.8946], device='cuda:0', grad_fn=<SumBackward1>)
tensor([0.7404], device='cuda:0', grad_fn=<SumBackward1>)
tensor([-0.1099], device='cuda:0', grad_fn=<SumBackward1>)
tensor([-0.0498], device='cuda:0', grad_fn=<SumBackward1>)
