## MB-iSTFT-VITS2 inference

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import IPython.display as ipd
import librosa

import os
import json
import math

import requests
import torch
import torchaudio
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader

import commons
import utils
from data_utils_speaker_tone_lang import TextAudioSpeakerToneLangLoader, TextAudioSpeakerToneLangCollate
from models import SynthesizerTrn
from text.symbols import symbols
from text import text_to_sequence

from scipy.io.wavfile import write
import re

In [3]:
#- device setting
if torch.cuda.is_available() is True:
    device = "cuda:0"
else:
    device = "cpu"

In [ ]:
from utils import load_wav_to_torch_2
from mel_processing import mel_spectrogram_torch

def file_to_mel(file_path, hps):
    """
    Uses the exact same pipeline as training: load_wav_to_torch_2 + mel_spectrogram_torch.
    """
    audio, _ = load_wav_to_torch_2(file_path, target_sampling_rate=hps.data.sampling_rate)
    audio_norm = (audio / hps.data.max_wav_value).unsqueeze(0)
    return mel_spectrogram_torch(
        audio_norm, hps.data.filter_length, hps.data.n_mel_channels,
        hps.data.sampling_rate, hps.data.hop_length, hps.data.win_length,
        hps.data.mel_fmin, hps.data.mel_fmax, center=False,
    )  # [1, n_mels, time]

In [5]:
def get_text(text, hps, lid):
    lang_code = "ky" if lid == 0 else "ru"
    text_norm = text_to_sequence(text, hps.data.text_cleaners, lang_code)
    if hps.data.add_blank:
        text_norm = commons.intersperse(text_norm, 0)
    text_norm = torch.LongTensor(text_norm)
    return text_norm

def vcms(inputstr, sid, tid, lid, spec_ref): # multi
    fltstr = re.sub(r"[\[\]\(\)\{\}]", "", inputstr)
    #fltstr = langdetector(fltstr) #- optional for cjke/cjks type cleaners
    stn_tst = get_text(fltstr, hps, lid)
    speed = 1
    with torch.no_grad():
        x_tst = stn_tst.to(device).unsqueeze(0)
        x_tst_lengths = torch.LongTensor([stn_tst.size(0)]).to(device)
        print(x_tst_lengths)
        print(x_tst_lengths.shape)
        sid = torch.LongTensor([sid]).to(device)
        tid = torch.LongTensor([tid]).to(device)
        lid = torch.LongTensor([lid]).to(device)
        audio = net_g.infer(x_tst, y=spec_ref, sid=sid, tid=tid, lid=lid, noise_scale=0.67, noise_scale_w=0.8, length_scale=1 / speed)[0][
            0, 0].data.cpu().float().numpy()

    ipd.display(ipd.Audio(audio, rate=hps.data.sampling_rate, normalize=True))

In [6]:
# - paths
path_to_config = "/mnt/d/elevenlabs/config.json" 
path_to_model = "/mnt/d/elevenlabs/G_139800.pth"  

path_to_config = "/mnt/d/super_last/config.json" 
path_to_model = "/mnt/d/super_last/G_688000.pth"

# path_to_config = "/mnt/d/youtube/config.json" 
# path_to_model = "/mnt/d/youtube/G_42000.pth"

# path_to_config = "/home/k_arzymatov/PycharmProjects/VITS100/logs/mbank_sdp/config.json" 
# path_to_model = "/home/k_arzymatov/PycharmProjects/VITS100/logs/mbank_sdp/G_98000.pth"

In [7]:
hps = utils.get_hparams_from_file(path_to_config)

if "use_mel_posterior_encoder" in hps.model.keys() and hps.model.use_mel_posterior_encoder == True:
    print("Using mel posterior encoder for VITS2")
    posterior_channels = 80  # vits2
    hps.data.use_mel_posterior_encoder = True
else:
    print("Using lin posterior encoder for VITS1")
    posterior_channels = hps.data.filter_length // 2 + 1
    hps.data.use_mel_posterior_encoder = False

net_g = SynthesizerTrn(
    len(symbols),
    posterior_channels,
    hps.train.segment_size // hps.data.hop_length,
    **hps.model).to(device)
_ = net_g.eval()

_ = utils.load_checkpoint(path_to_model, net_g, None)

Using mel posterior encoder for VITS2
Multi-band iSTFT VITS2


/home/k_arzymatov/miniconda3/envs/universal_models_312/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [8]:
total_params = sum(p.numel() for p in net_g.parameters())
print(total_params)

40404465


In [ ]:
# ref_audio = "/mnt/d/elevenlabs_generate_kyrgyz_voices/output/noble_butler/00001_001_news_01-05_007_1_Timur_neutral_kg.wav"
# spec_filename = "/mnt/d/elevenlabs_generate_kyrgyz_voices/output/noble_butler/00001_001_news_01-05_007_1_Timur_neutral_kg.mel.pt"

ref_audio = "/mnt/d/data_gathering_diarization_cleaning/output/2cTytn8JvZA/segments/SPEAKER_00/segment_0001.wav"

# ref_audio = "/mnt/d/studio_audio_flat/wavs/00000_000_inter_sounds_neutral_040_1_Aiganysh_strict_kg.wav"
# ref_audio = "/mnt/d/00000_000_addresses_004_1_Timur_neutral_kg.wav"

# ref_audio = "/mnt/d/qwen_girl1.wav"

# Use the same mel computation as training (critical for reference encoder!)
spec_ref = file_to_mel(ref_audio, hps).to(device)

# Or load pre-computed mel from training (already in correct format):
# spec_filename = "/mnt/d/00189_008_ru_general_044_19_Timur_neutral_ru.mel.pt"
# spec_ref = torch.load(spec_filename, weights_only=True).to(device).unsqueeze(0)

In [43]:
ipd.display(ipd.Audio(ref_audio, rate=hps.data.sampling_rate, normalize=False))

In [50]:
c = " рыноктук шартка ылайыкташкан ушул ишканалар өнөр жай , курулуш , транспорт , соода же тейлөөнүн башка тармактарына таандык . "
# c = "бишкек"
# c = " <cough> сураныч мен максат эмесмин . "
# c = "Главный транспортный узел, промышленный и административный центр страны. Современный культурный, политический и экономический центр республики."
# c = "шаардын жаныбарлар дүйнөсүнүн негизин палеарктикалык ландшафттын маданий фаунасынын типтүү өкүлдөрү түзөт. сүт эмүүчүлөрдүн негизгилери жарганаттар."
vcms(c, sid=0, tid=1, lid=0, spec_ref=spec_ref)

tensor([253], device='cuda:0')
torch.Size([1])


AttributeError: 'Multiband_iSTFT_Generator' object has no attribute 'cond'

In [51]:
net_g

SynthesizerTrn(
  (enc_p): TextEncoder(
    (emb): Embedding(157, 192)
    (encoder): Encoder(
      (drop): Dropout(p=0.1, inplace=False)
      (attn_layers): ModuleList(
        (0-5): 6 x MultiHeadAttention(
          (conv_q): Conv1d(192, 192, kernel_size=(1,), stride=(1,))
          (conv_k): Conv1d(192, 192, kernel_size=(1,), stride=(1,))
          (conv_v): Conv1d(192, 192, kernel_size=(1,), stride=(1,))
          (conv_o): Conv1d(192, 192, kernel_size=(1,), stride=(1,))
          (drop): Dropout(p=0.1, inplace=False)
        )
      )
      (norm_layers_1): ModuleList(
        (0-5): 6 x LayerNorm()
      )
      (ffn_layers): ModuleList(
        (0-5): 6 x FFN(
          (conv_1): Conv1d(192, 768, kernel_size=(3,), stride=(1,))
          (conv_2): Conv1d(768, 192, kernel_size=(3,), stride=(1,))
          (drop): Dropout(p=0.1, inplace=False)
        )
      )
      (norm_layers_2): ModuleList(
        (0-5): 6 x LayerNorm()
      )
    )
    (proj): Conv1d(192, 384, kernel_siz

In [32]:
text = get_text(c, hps, lid=0).to(device).unsqueeze(0)
text_lengths = torch.LongTensor([text.size(1)]).to(device)
print(text)
print(text_lengths)

with torch.no_grad():
    audio = net_g.infer(text, y=spec_ref)[0][0, 0].data.cpu().float().numpy()

ipd.display(ipd.Audio(audio, rate=hps.data.sampling_rate, normalize=True))

tensor([[ 0,  3,  0, 64,  0, 76,  0, 59,  0, 61,  0, 56,  0, 66,  0, 67,  0, 56,
          0,  3,  0, 73,  0, 45,  0, 64,  0, 66,  0, 56,  0, 45,  0,  3,  0, 76,
          0, 57,  0, 45,  0, 55,  0, 76,  0, 56,  0, 66,  0, 45,  0, 73,  0, 56,
          0, 45,  0, 59,  0,  3,  0, 67,  0, 73,  0, 67,  0, 57,  0,  3,  0, 54,
          0, 73,  0, 56,  0, 45,  0, 59,  0, 45,  0, 57,  0, 45,  0, 64,  0,  3,
          0, 62,  0, 59,  0, 62,  0, 64,  0,  3,  0, 52,  0, 45,  0, 55,  0,  3,
          0,  5,  0,  3,  0, 56,  0, 67,  0, 64,  0, 67,  0, 57,  0, 67,  0, 73,
          0,  3,  0,  5,  0,  3,  0, 66,  0, 64,  0, 45,  0, 59,  0, 65,  0, 63,
          0, 61,  0, 64,  0, 66,  0,  3,  0,  5,  0,  3,  0, 65,  0, 61,  0, 61,
          0, 49,  0, 45,  0,  3,  0, 52,  0, 50,  0,  3,  0, 66,  0, 50,  0, 55,
          0, 57,  0, 62,  0, 62,  0, 59,  0, 68,  0, 59,  0,  3,  0, 46,  0, 45,
          0, 73,  0, 56,  0, 45,  0,  3,  0, 66,  0, 45,  0, 64,  0, 58,  0, 45,
          0, 56,  0, 66,  0,

In [34]:
spec_ref.dtype

torch.float32

In [19]:
timur_audio_1 = "/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep_34_Timur_neutral_kg.wav"
timur_spec_1 = torch.load("/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep_34_Timur_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_timur_1 = net_g.ref_enc(timur_spec_1)

timur_audio_2 = "/mnt/d/studio_audio_flat/wavs/00318_007_sales_001_commas_sep_31_Timur_neutral_kg.wav"
timur_spec_2 = torch.load("/mnt/d/studio_audio_flat/wavs/00318_007_sales_001_commas_sep_31_Timur_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_timur_2 = net_g.ref_enc(timur_spec_2)

aiganysh_audio_1 = "/mnt/d/studio_audio_flat/wavs/00349_007_sales_001_commas_sep_35_Aiganysh_strict_kg.wav"
aiganysh_spec_1 = torch.load("/mnt/d/studio_audio_flat/wavs/00349_007_sales_001_commas_sep_35_Aiganysh_strict_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_aiganysh_1 = net_g.ref_enc(aiganysh_spec_1)

aiganysh_audio_2 = "/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep-2_35_Aiganysh_neutral_kg.wav"
aiganysh_spec_2 = torch.load("/mnt/d/studio_audio_flat/wavs/00348_007_sales_001_commas_sep-2_35_Aiganysh_neutral_kg.mel.pt").unsqueeze(0).transpose(1, 2).to(device)
g_aiganysh_2 = net_g.ref_enc(aiganysh_spec_2)

# random_audio_1 = "/mnt/d/data_gathering_diarization_cleaning/output/2cTytn8JvZA/segments/SPEAKER_00/segment_0001.wav"
# random_spec_1 =  file_to_mel(random_audio_1).to(device)
# g_random_1 = net_g.ref_enc(random_spec_1)

# random_audio_2 = "/mnt/d/qwen_girl1.wav"
# random_spec_2 =  file_to_mel(random_audio_2).to(device)
# g_random_2 = net_g.ref_enc(random_audio_2)

In [20]:
g_timur_1.shape

torch.Size([1, 256])

In [21]:
print(F.cosine_similarity(g_timur_1, g_timur_2))
print(F.cosine_similarity(g_aiganysh_1, g_aiganysh_2))
print(F.cosine_similarity(g_timur_1, g_aiganysh_1))
print(F.cosine_similarity(g_timur_2, g_aiganysh_2))

tensor([0.8946], device='cuda:0', grad_fn=<SumBackward1>)
tensor([0.7404], device='cuda:0', grad_fn=<SumBackward1>)
tensor([-0.1099], device='cuda:0', grad_fn=<SumBackward1>)
tensor([-0.0498], device='cuda:0', grad_fn=<SumBackward1>)


In [22]:
print(g_timur_1.norm())
print(g_aiganysh_1.norm())

tensor(6.7531, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)
tensor(5.6674, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)


In [26]:
g_timur_2

tensor([[ 1.4761e-01,  7.0810e-02, -1.0288e+00,  4.4682e-02, -7.5046e-01,
          2.1003e-01,  1.9097e-01,  1.5651e-01, -3.5517e-01,  3.4854e-01,
         -1.5358e-01, -5.2020e-01,  4.5163e-01,  5.6531e-01, -9.2324e-02,
          5.4657e-02,  7.4301e-02, -3.3631e-01, -1.9784e-04, -1.3144e-03,
          3.7525e-01,  7.2918e-02, -3.2693e-01,  1.6499e-01, -6.4341e-02,
          3.8286e-01, -2.9430e-01,  1.2473e+00, -4.9034e-01, -2.4999e-01,
         -5.2474e-01,  1.6096e-01, -1.7116e-01, -2.5908e-01, -7.3799e-01,
          2.4655e-02,  1.6939e-01,  1.7423e-01, -6.6184e-01, -2.3310e-01,
         -3.6992e-02, -2.4220e-01, -7.9857e-01, -2.2159e-01, -1.0941e-01,
          1.8237e-01, -1.8852e-01,  2.5225e-01,  8.2448e-01,  2.7356e-01,
          1.8093e-01, -3.1195e-01,  1.6967e-01,  7.5842e-02, -2.5020e-01,
          1.4964e+00, -6.8878e-02, -1.1687e+00,  1.6187e-02,  6.9931e-02,
          6.1889e-01,  1.2327e-01,  2.3718e-02, -1.2146e-01,  3.5550e-03,
          3.4294e-01,  1.9458e-01, -1.

In [23]:
print(g_timur_2.norm())
print(g_aiganysh_2.norm())

tensor(6.6434, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)
tensor(5.6054, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)


In [46]:
print(g_timur_1.norm())
print(g_aiganysh_1.norm())

tensor(6.7531, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)
tensor(5.6674, device='cuda:0', grad_fn=<LinalgVectorNormBackward0>)


In [57]:
import pymorphy3
morph = pymorphy3.MorphAnalyzer()
parsed = morph.parse("адал")


for p in parsed:
    if 'UNKN' not in p.tag:
        print(p.tag)

VERB,perf,tran masc,sing,past,indc
VERB,impf,intr masc,sing,past,indc
NOUN,anim,masc sing,nomn
NOUN,anim,masc,Name sing,nomn


In [56]:
parsed[0]

Parse(word='адал', tag=OpencorporaTag('VERB,perf,tran masc,sing,past,indc'), normal_form='адать', score=0.5111111111111111, methods_stack=((DictionaryAnalyzer(), 'дал', 884, 1), (UnknownPrefixAnalyzer(score_multiplier=0.5), 'а')))

In [1]:
from pyannote.audio import Model
model = Model.from_pretrained("pyannote/wespeaker-voxceleb-resnet34-LM")

/home/k_arzymatov/miniconda3/envs/universal_models_312/lib/python3.12/site-packages/pyannote/audio/core/io.py:47: UserWarning: 
torchcodec is not installed correctly so built-in audio decoding will fail. Solutions are:
* use audio preloaded in-memory as a {'waveform': (channel, time) torch.Tensor, 'sample_rate': int} dictionary;
* fix torchcodec installation. Error message was:

Could not load libtorchcodec. Likely causes:
          1. FFmpeg is not properly installed in your environment. We support
             versions 4, 5, 6 and 7.
          2. The PyTorch version (2.7.1+cu128) is not compatible with
             this version of TorchCodec. Refer to the version compatibility
             table:
             https://github.com/pytorch/torchcodec?tab=readme-ov-file#installing-torchcodec.
          3. Another runtime dependency; see exceptions below.
        The following exceptions were raised as we tried to load libtorchcodec:
        
[start of libtorchcodec loading traceback]
liba

ModuleNotFoundError: No module named 'pyannote.database'

In [16]:
!pip install opentelemetry-api --no-deps

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [18]:
from pyannote.audio import Model

ModuleNotFoundError: No module named 'opentelemetry.exporter'

In [20]:
import torch 
torch.__version__

'2.7.1+cu128'